### ISSUE TITLE
Issue on additional CT-Logs sources in config file

### ISSUE THREAD

**Issue by vegeta2206** [d-Rickyy-b/certstream-server-go#62]
These lines in config.sample.yaml contains a small error :

```
general:
  additional_logs:
    - url: https://ct.googleapis.com/logs/us1/mirrors/digicert_nessie2022/
      operator: "DigiCert"
      description: "DigiCert Nessie2022 log"

```
To correct, simply remove the slash at the end, resolve error :

```
general:
  additional_logs:
    - url: https://ct.googleapis.com/logs/us1/mirrors/digicert_nessie2022
      operator: "DigiCert"
      description: "DigiCert Nessie2022 log"

```

**You will avoid this error :** 
2025/05/04 07:32:51 config.go:212: Ignoring invalid additional log URL:  https://ct.googleapis.com/logs/us1/argon2025h1/
